In [1]:
from bs4 import BeautifulSoup

In [2]:
with open('htmls/page2.html') as f:
     content=f.read()

In [4]:
soup=BeautifulSoup(content,"html.parser")

In [6]:
soup

<!DOCTYPE html>

<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-us"> <!--<![endif]-->
<head>
<title>
    All products | Books to Scrape - Sandbox
</title>
<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
<meta content="24th Jun 2016 09:29" name="created"/>
<meta content="" name="description"/>
<meta content="width=device-width" name="viewport"/>
<meta content="NOARCHIVE,NOCACHE" name="robots"/>
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
<link href="../static/oscar/favicon.ico" rel="shortcut icon"/>
<link href="../static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
<link href="../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
<link href="../static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
</head>
<body class="default" id="default">
<header class="header container-fluid">
<div class="page_inner">
<div class="row">
<div class="col-sm-8 h1"><a href="../index.html">Books to Scrape</a><small> We love being scraped!</small>
</div>
</div>
</div>
</header>
<div class="container-fluid page">
<div class="page_inner">
<ul class="breadcrumb">
<li>
<a href="../index.html">Home</a>
</li>
<li class="active">All products</li>
</ul>
<div class="row">
<aside class="sidebar col-sm-4 col-md-3">
<div id="promotions_left">
</div>
<div class="side_categories">
<ul class="nav nav-list">
<li>
<a href="category/books_1/index.html">

                                Books

                        </a>
<ul>
<li>
<a href="category/books/travel_2/index.html">

                                Travel

                        </a>
</li>
<li>
<a href="category/books/mystery_3/index.html">

                                Mystery

                        </a>
</li>
<li>
<a href="category/books/historical-fiction_4/index.html">

                                Historical Fiction

                        </a>
</li>
<li>
<a href="category/books/sequential-art_5/index.html">

                                Sequential Art

                        </a>
</li>
<li>
<a href="category/books/classics_6/index.html">

                                Classics

                        </a>
</li>
<li>
<a href="category/books/philosophy_7/index.html">

                                Philosophy

                        </a>
</li>
<li>
<a href="category/books/romance_8/index.html">

                                Romance

                        </a>
</li>
<li>
<a href="category/books/womens-fiction_9/index.html">

                                Womens Fiction

                        </a>
</li>
<li>
<a href="category/books/fiction_10/index.html">

                                Fiction

                        </a>
</li>
<li>
<a href="category/books/childrens_11/index.html">

                                Childrens

                        </a>
</li>
<li>
<a href="category/books/religion_12/index.html">

                                Religion

                        </a>
</li>
<li>
<a href="category/books/nonfiction_13/index.html">

                                Nonfiction

                        </a>
</li>
<li>
<a href="category/books/music_14/index.html">

                                Music

                        </a>
</li>
<li>
<a href="category/books/default_15/index.html">

                                Default

                        </a>
</li>
<li>
<a href="category/books/science-fiction_16/index.html">

                                Science Fiction

                        </a>
</li>
<li>
<a href="category/books/sports-and-games_17/index.html">

                                Sports and Games

                        </a>
</li>
<li>
<a href="category/books/add-a-comment_18/index.html">

                                Add a comment

                        </a>
</li>
<li>
<a href="category/books/fantasy_19/index.html">

                                Fantasy

                        </a>
</li>
<li>
<a href="category/books/new-adult_20/index.html">

                                New Adult

                        </a>
</li>
<li>
<a href="category/books/young-adult_21/index.html">

                                Young Adult

                        </a>
</li>
<li>
<a href="category/books/science_22/index.html">

                                Science

                        </a>
</li>
<li>
<a href="category/books/poetry_23/index.html">

                                Poetry

                        </a>
</li>
<li>
<a href="category/books/paranormal_24/index.html">

                                Paranormal

                        </a>
</li>
<li>
<a href="category/books/art_25/index.html">

                                Art

                        </a>
</li>
<li>
<a href="category/books/psychology_26/index.html">

                                Psychology

                        </a>
</li>
<li>
<a href="category/books/autobiography_27/index.html">

                                Autobiography

                        </a>
</li>
<li>
<a href="category/books/parenting_28/index.html">

                                Parenting

                        </a>
</li>
<li>
<a href="category/books/adult-fiction_29/index.html">

                                Adult Fiction

                        </a>
</li>
<li>
<a href="category/books/humor_30/index.html">

                                Humor

                        </a>
</li>
<li>
<a href="category/books/horror_31/index.html">

                                Horror

                        </a>
</li>
<li>
<a href="category/books/history_32/index.html">

                                History

                        </a>
</li>
<li>
<a href="category/books/food-and-drink_33/index.html">

                                Food and Drink

                        </a>
</li>
<li>
<a href="category/books/christian-fiction_34/index.html">

                                Christian Fiction

                        </a>
</li>
<li>
<a href="category/books/business_35/index.html">

                                Business

                        </a>
</li>
<li>
<a href="category/books/biography_36/index.html">

                                Biography

                        </a>
</li>
<li>
<a href="category/books/thriller_37/index.html">

                                Thriller

                        </a>
</li>
<li>
<a href="category/books/contemporary_38/index.html">

                                Contemporary

                        </a>
</li>
<li>
<a href="category/books/spirituality_39/index.html">

                                Spirituality

                        </a>
</li>
<li>
<a href="category/books/academic_40/index.html">

                                Academic

                        </a>
</li>
<li>
<a href="category/books/self-help_41/index.html">

                                Self Help

                        </a>
</li>
<li>
<a href="category/books/historical_42/index.html">

                                Historical

                        </a>
</li>
<li>
<a href="category/books/christian_43/index.html">

                                Christian

                        </a>
</li>
<li>
<a href="category/books/suspense_44/index.html">

                                Suspense

                        </a>
</li>
<li>
<a href="category/books/short-stories_45/index.html">

                                Short Stories

                        </a>
</li>
<li>
<a href="category/books/novels_46/index.html">

                                Novels

                        </a>
</li>
<li>
<a href="category/books/health_47/index.html">

                                Health

                        </a>
</li>
<li>
<a href="category/books/politics_48/index.html">

                                Politics

                        </a>
</li>
<li>
<a href="category/books/cultural_49/index.html">

                                Cultural

                        </a>
</li>
<li>
<a href="category/books/erotica_50/index.html">

                                Erotica

                        </a>
</li>
<li>
<a href="category/books/crime_51/index.html">

                                Crime

                        </a>
</li>
</ul></li>
</ul>
</div>
</aside>
<div class="col-sm-8 col-md-9">
<div class="page-header action">
<h1>All products</h1>
</div>
<div id="messages">
</div>
<div id="promotions">
</div>
<form class="form-horizontal" method="get">
<div style="display:none">
</div>
<strong>1000</strong> results - showing <strong>21</strong> to <strong>40</strong>.




    </form>
<section>
<div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>
<div>
<ol class="row">
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="in-her-wake_980/index.html"><img alt="In Her Wake" class="thumbnail" src="../media/cache/5d/72/5d72709c6a7a9584a4d1cf07648bfce1.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="in-her-wake_980/index.html" title="In Her Wake">In Her Wake</a></h3>
<div class="product_price">
<p class="price_color">Ã‚Â£12.84</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="how-music-works_979/index.html"><img alt="How Music Works" class="thumbnail" src="../media/cache/5c/c8/5cc8e107246cb478960d4f0aba1e1c8e.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="how-music-works_979/index.html" title="How Music Works">How Music Works</a></h3>
<div class="product_price">
<p class="price_color">Ã‚Â£37.32</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html"><img alt="Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More" class="thumbnail" src="../media/cache/9f/59/9f59f01fa916a7bb8f0b28a4012179a4.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html" title="Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More">Foolproof Preserving: A Guide ...</a></h3>
<div class="product_price">
<p class="price_color">Ã‚Â£30.52</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="chase-me-paris-nights-2_977/index.html"><img alt="Chase Me (Paris Nights #2)" class="thumbnail" src="../media/cache/9c/2e/9c2e0eb8866b8e3f3b768994fd3d1c1a.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="chase-me-paris-nights-2_977/index.html" title="Chase Me (Paris Nights #2)">Chase Me (Paris Nights ...</a></h3>
<div class="product_price">
<p class="price_color">Ã‚Â£25.27</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="black-dust_976/index.html"><img alt="Black Dust" class="thumbnail" src="../media/cache/44/cc/44ccc99c8f82c33d4f9d2afa4ef25787.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="black-dust_976/index.html" title="Black Dust">Black Dust</a></h3>
<div class="product_price">
<p class="price_color">Ã‚Â£34.53</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="birdsong-a-story-in-pictures_975/index.html"><img alt="Birdsong: A Story in Pictures" class="thumbnail" src="../media/cache/af/6e/af6e796160fe63e0cf19d44395c7ddf2.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="birdsong-a-story-in-pictures_975/index.html" title="Birdsong: A Story in Pictures">Birdsong: A Story in ...</a></h3>
<div class="product_price">
<p class="price_color">Ã‚Â£54.64</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html"><img alt="America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana" class="thumbnail" src="../media/cache/ef/0b/ef0bed08de4e083dba5e20fdb98d9c36.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html" title="America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana">America's Cradle of Quarterbacks: ...</a></h3>
<div class="product_price">
<p class="price_color">Ã‚Â£22.50</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="aladdin-and-his-wonderful-lamp_973/index.html"><img alt="Aladdin and His Wonderful Lamp" class="thumbnail" src="../media/cache/d6/da/d6da0371958068bbaf39ea9c174275cd.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="aladdin-and-his-wonderful-lamp_973/index.html" title="Aladdin and His Wonderful Lamp">Aladdin and His Wonderful ...</a></h3>
<div class="product_price">
<p class="price_color">Ã‚Â£53.13</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html"><img alt="Worlds Elsewhere: Journeys Around ShakespeareÃ¢Â€Â™s Globe" class="thumbnail" src="../media/cache/2e/98/2e98c332bf8563b584784971541c4445.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html" title="Worlds Elsewhere: Journeys Around ShakespeareÃ¢Â€Â™s Globe">Worlds Elsewhere: Journeys Around ...</a></h3>
<div class="product_price">
<p class="price_color">Ã‚Â£40.30</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="wall-and-piece_971/index.html"><img alt="Wall and Piece" class="thumbnail" src="../media/cache/a5/41/a5416b9646aaa7287baa287ec2590270.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="wall-and-piece_971/index.html" title="Wall and Piece">Wall and Piece</a></h3>
<div class="product_price">
<p class="price_color">Ã‚Â£44.18</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html"><img alt="The Four Agreements: A Practical Guide to Personal Freedom" class="thumbnail" src="../media/cache/0f/7e/0f7ee69495c0df1d35723f012624a9f8.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html" title="The Four Agreements: A Practical Guide to Personal Freedom">The Four Agreements: A ...</a></h3>
<div class="product_price">
<p class="price_color">Ã‚Â£17.66</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">

In [8]:
soup.header

<header class="header container-fluid">
<div class="page_inner">
<div class="row">
<div class="col-sm-8 h1"><a href="../index.html">Books to Scrape</a><small> We love being scraped!</small>
</div>
</div>
</div>
</header>

In [13]:
soup.h1

In [14]:
soup.h1.text

'All products'

In [19]:
h3s=soup.find_all("h3")
h3s

[<h3><a href="in-her-wake_980/index.html" title="In Her Wake">In Her Wake</a></h3>,
 <h3><a href="how-music-works_979/index.html" title="How Music Works">How Music Works</a></h3>,
 <h3><a href="foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html" title="Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More">Foolproof Preserving: A Guide ...</a></h3>,
 <h3><a href="chase-me-paris-nights-2_977/index.html" title="Chase Me (Paris Nights #2)">Chase Me (Paris Nights ...</a></h3>,
 <h3><a href="black-dust_976/index.html" title="Black Dust">Black Dust</a></h3>,
 <h3><a href="birdsong-a-story-in-pictures_975/index.html" title="Birdsong: A Story in Pictures">Birdsong: A Story in ...</a></h3>,
 <h3><a href="americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html" title="America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana">America's Cradle of Quarterbacks: ...</a></h3>,
 <h3><a href="aladdin-and-his-wonderful-lamp_973/index.html" title="Aladdin and His Wonderful Lamp">Aladdin and His Wonderful ...</a></h3>,
 <h3><a href="worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html" title="Worlds Elsewhere: Journeys Around ShakespeareÃ¢Â€Â™s Globe">Worlds Elsewhere: Journeys Around ...</a></h3>,
 <h3><a href="wall-and-piece_971/index.html" title="Wall and Piece">Wall and Piece</a></h3>,
 <h3><a href="the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html" title="The Four Agreements: A Practical Guide to Personal Freedom">The Four Agreements: A ...</a></h3>,
 <h3><a href="the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html" title="The Five Love Languages: How to Express Heartfelt Commitment to Your Mate">The Five Love Languages: ...</a></h3>,
 <h3><a href="the-elephant-tree_968/index.html" title="The Elephant Tree">The Elephant Tree</a></h3>,
 <h3><a href="the-bear-and-the-piano_967/index.html" title="The Bear and the Piano">The Bear and the ...</a></h3>,
 <h3><a href="sophies-world_966/index.html" title="Sophie's World">Sophie's World</a></h3>,
 <h3><a href="penny-maybe_965/index.html" title="Penny Maybe">Penny Maybe</a></h3>,
 <h3><a href="maude-1883-1993she-grew-up-with-the-country_964/index.html" title="Maude (1883-1993):She Grew Up with the country">Maude (1883-1993):She Grew Up ...</a></h3>,
 <h3><a href="in-a-dark-dark-wood_963/index.html" title="In a Dark, Dark Wood">In a Dark, Dark ...</a></h3>,
 <h3><a href="behind-closed-doors_962/index.html" title="Behind Closed Doors">Behind Closed Doors</a></h3>,
 <h3><a href="you-cant-bury-them-all-poems_961/index.html" title="You can't bury them all: Poems">You can't bury them ...</a></h3>]

In [21]:
for h3 in h3s:
    print(h3.find('a')['title'])

In Her Wake
How Music Works
Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More
Chase Me (Paris Nights #2)
Black Dust
Birdsong: A Story in Pictures
America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana
Aladdin and His Wonderful Lamp
Worlds Elsewhere: Journeys Around ShakespeareÃ¢Â€Â™s Globe
Wall and Piece
The Four Agreements: A Practical Guide to Personal Freedom
The Five Love Languages: How to Express Heartfelt Commitment to Your Mate
The Elephant Tree
The Bear and the Piano
Sophie's World
Penny Maybe
Maude (1883-1993):She Grew Up with the country
In a Dark, Dark Wood
Behind Closed Doors
You can't bury them all: Poems

In [24]:
soup.article

<article class="product_pod">
<div class="image_container">
<a href="in-her-wake_980/index.html"><img alt="In Her Wake" class="thumbnail" src="../media/cache/5d/72/5d72709c6a7a9584a4d1cf07648bfce1.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="in-her-wake_980/index.html" title="In Her Wake">In Her Wake</a></h3>
<div class="product_price">
<p class="price_color">Ã‚Â£12.84</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

In [25]:
soup.find_all('article')

[<article class="product_pod">
 <div class="image_container">
 <a href="in-her-wake_980/index.html"><img alt="In Her Wake" class="thumbnail" src="../media/cache/5d/72/5d72709c6a7a9584a4d1cf07648bfce1.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="in-her-wake_980/index.html" title="In Her Wake">In Her Wake</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£12.84</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="how-music-works_979/index.html"><img alt="How Music Works" class="thumbnail" src="../media/cache/5c/c8/5cc8e107246cb478960d4f0aba1e1c8e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="how-music-works_979/index.html" title="How Music Works">How Music Works</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£37.32</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html"><img alt="Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More" class="thumbnail" src="../media/cache/9f/59/9f59f01fa916a7bb8f0b28a4012179a4.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html" title="Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More">Foolproof Preserving: A Guide ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£30.52</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="chase-me-paris-nights-2_977/index.html"><img alt="Chase Me (Paris Nights #2)" class="thumbnail" src="../media/cache/9c/2e/9c2e0eb8866b8e3f3b768994fd3d1c1a.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="chase-me-paris-nights-2_977/index.html" title="Chase Me (Paris Nights #2)">Chase Me (Paris Nights ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£25.27</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="black-dust_976/index.html"><img alt="Black Dust" class="thumbnail" src="../media/cache/44/cc/44ccc99c8f82c33d4f9d2afa4ef25787.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="black-dust_976/index.html" title="Black Dust">Black Dust</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£34.53</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="birdsong-a-story-in-pictures_975/index.html"><img alt="Birdsong: A Story in Pictures" class="thumbnail" src="../media/cache/af/6e/af6e796160fe63e0cf19d44395c7ddf2.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="birdsong-a-story-in-pictures_975/index.html" title="Birdsong: A Story in Pictures">Birdsong: A Story in ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£54.64</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html"><img alt="America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana" class="thumbnail" src="../media/cache/ef/0b/ef0bed08de4e083dba5e20fdb98d9c36.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html" title="America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana">America's Cradle of Quarterbacks: ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£22.50</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="aladdin-and-his-wonderful-lamp_973/index.html"><img alt="Aladdin and His Wonderful Lamp" class="thumbnail" src="../media/cache/d6/da/d6da0371958068bbaf39ea9c174275cd.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="aladdin-and-his-wonderful-lamp_973/index.html" title="Aladdin and His Wonderful Lamp">Aladdin and His Wonderful ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£53.13</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html"><img alt="Worlds Elsewhere: Journeys Around ShakespeareÃ¢Â€Â™s Globe" class="thumbnail" src="../media/cache/2e/98/2e98c332bf8563b584784971541c4445.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html" title="Worlds Elsewhere: Journeys Around ShakespeareÃ¢Â€Â™s Globe">Worlds Elsewhere: Journeys Around ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£40.30</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="wall-and-piece_971/index.html"><img alt="Wall and Piece" class="thumbnail" src="../media/cache/a5/41/a5416b9646aaa7287baa287ec2590270.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="wall-and-piece_971/index.html" title="Wall and Piece">Wall and Piece</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£44.18</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html"><img alt="The Four Agreements: A Practical Guide to Personal Freedom" class="thumbnail" src="../media/cache/0f/7e/0f7ee69495c0df1d35723f012624a9f8.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html" title="The Four Agreements: A Practical Guide to Personal Freedom">The Four Agreements: A ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£17.66</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html"><img alt="The Five Love Languages: How to Express Heartfelt Commitment to Your Mate" class="thumbnail" src="../media/cache/38/c5/38c56fba316c07305643a8065269594e.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html" title="The Five Love Languages: How to Express Heartfelt Commitment to Your Mate">The Five Love Languages: ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£31.05</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="the-elephant-tree_968/index.html"><img alt="The Elephant Tree" class="thumbnail" src="../media/cache/5d/7e/5d7ecde8e81513eba8a64c9fe000744b.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-elephant-tree_968/index.html" title="The Elephant Tree">The Elephant Tree</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£23.82</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="the-bear-and-the-piano_967/index.html"><img alt="The Bear and the Piano" class="thumbnail" src="../media/cache/cf/bb/cfbb5e62715c6d888fd07794c9bab5d6.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-bear-and-the-piano_967/index.html" title="The Bear and the Piano">The Bear and the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£36.89</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="sophies-world_966/index.html"><img alt="Sophie's World" class="thumbnail" src="../media/cache/65/71/6571919836ec51ed54f0050c31d8a0cd.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="sophies-world_966/index.html" title="Sophie's World">Sophie's World</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£15.94</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="penny-maybe_965/index.html"><img alt="Penny Maybe" class="thumbnail" src="../media/cache/12/53/1253c21c5ef3c6d075c5fa3f5fecee6a.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="penny-maybe_965/index.html" title="Penny Maybe">Penny Maybe</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£33.29</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="maude-1883-1993she-grew-up-with-the-country_964/index.html"><img alt="Maude (1883-1993):She Grew Up with the country" class="thumbnail" src="../media/cache/f5/88/f5889d038f5d8e949b494d147c2dcf54.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="maude-1883-1993she-grew-up-with-the-country_964/index.html" title="Maude (1883-1993):She Grew Up with the country">Maude (1883-1993):She Grew Up ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£18.02</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="in-a-dark-dark-wood_963/index.html"><img alt="In a Dark, Dark Wood" class="thumbnail" src="../media/cache/23/85/238570a1c284e730dbc737a7e631ae2b.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="in-a-dark-dark-wood_963/index.html" title="In a Dark, Dark Wood">In a Dark, Dark ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£19.63</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="behind-closed-doors_962/index.html"><img alt="Behind Closed Doors" class="thumbnail" src="../media/cache/e1/5c/e15c289ba58cea38519e1281e859f0c1.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="behind-closed-doors_962/index.html" title="Behind Closed Doors">Behind Closed Doors</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£52.22</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="you-cant-bury-them-all-poems_961/index.html"><img alt="You can't bury them all: Poems" class="thumbnail" src="../media/cache/e9/20/e9203b733126c4a0832a1c7885dc27cf.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="you-cant-bury-them-all-poems_961/index.html" title="You can't bury them all: Poems">You can't bury them ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£33.63</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>]

In [26]:
articles=soup.select("article.product_pod")
articles

[<article class="product_pod">
 <div class="image_container">
 <a href="in-her-wake_980/index.html"><img alt="In Her Wake" class="thumbnail" src="../media/cache/5d/72/5d72709c6a7a9584a4d1cf07648bfce1.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="in-her-wake_980/index.html" title="In Her Wake">In Her Wake</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£12.84</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="how-music-works_979/index.html"><img alt="How Music Works" class="thumbnail" src="../media/cache/5c/c8/5cc8e107246cb478960d4f0aba1e1c8e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="how-music-works_979/index.html" title="How Music Works">How Music Works</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£37.32</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html"><img alt="Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More" class="thumbnail" src="../media/cache/9f/59/9f59f01fa916a7bb8f0b28a4012179a4.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html" title="Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More">Foolproof Preserving: A Guide ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£30.52</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="chase-me-paris-nights-2_977/index.html"><img alt="Chase Me (Paris Nights #2)" class="thumbnail" src="../media/cache/9c/2e/9c2e0eb8866b8e3f3b768994fd3d1c1a.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="chase-me-paris-nights-2_977/index.html" title="Chase Me (Paris Nights #2)">Chase Me (Paris Nights ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£25.27</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="black-dust_976/index.html"><img alt="Black Dust" class="thumbnail" src="../media/cache/44/cc/44ccc99c8f82c33d4f9d2afa4ef25787.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="black-dust_976/index.html" title="Black Dust">Black Dust</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£34.53</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="birdsong-a-story-in-pictures_975/index.html"><img alt="Birdsong: A Story in Pictures" class="thumbnail" src="../media/cache/af/6e/af6e796160fe63e0cf19d44395c7ddf2.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="birdsong-a-story-in-pictures_975/index.html" title="Birdsong: A Story in Pictures">Birdsong: A Story in ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£54.64</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html"><img alt="America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana" class="thumbnail" src="../media/cache/ef/0b/ef0bed08de4e083dba5e20fdb98d9c36.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html" title="America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana">America's Cradle of Quarterbacks: ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£22.50</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="aladdin-and-his-wonderful-lamp_973/index.html"><img alt="Aladdin and His Wonderful Lamp" class="thumbnail" src="../media/cache/d6/da/d6da0371958068bbaf39ea9c174275cd.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="aladdin-and-his-wonderful-lamp_973/index.html" title="Aladdin and His Wonderful Lamp">Aladdin and His Wonderful ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£53.13</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html"><img alt="Worlds Elsewhere: Journeys Around ShakespeareÃ¢Â€Â™s Globe" class="thumbnail" src="../media/cache/2e/98/2e98c332bf8563b584784971541c4445.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html" title="Worlds Elsewhere: Journeys Around ShakespeareÃ¢Â€Â™s Globe">Worlds Elsewhere: Journeys Around ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£40.30</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="wall-and-piece_971/index.html"><img alt="Wall and Piece" class="thumbnail" src="../media/cache/a5/41/a5416b9646aaa7287baa287ec2590270.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="wall-and-piece_971/index.html" title="Wall and Piece">Wall and Piece</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£44.18</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html"><img alt="The Four Agreements: A Practical Guide to Personal Freedom" class="thumbnail" src="../media/cache/0f/7e/0f7ee69495c0df1d35723f012624a9f8.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html" title="The Four Agreements: A Practical Guide to Personal Freedom">The Four Agreements: A ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£17.66</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html"><img alt="The Five Love Languages: How to Express Heartfelt Commitment to Your Mate" class="thumbnail" src="../media/cache/38/c5/38c56fba316c07305643a8065269594e.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html" title="The Five Love Languages: How to Express Heartfelt Commitment to Your Mate">The Five Love Languages: ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£31.05</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="the-elephant-tree_968/index.html"><img alt="The Elephant Tree" class="thumbnail" src="../media/cache/5d/7e/5d7ecde8e81513eba8a64c9fe000744b.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-elephant-tree_968/index.html" title="The Elephant Tree">The Elephant Tree</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£23.82</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="the-bear-and-the-piano_967/index.html"><img alt="The Bear and the Piano" class="thumbnail" src="../media/cache/cf/bb/cfbb5e62715c6d888fd07794c9bab5d6.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-bear-and-the-piano_967/index.html" title="The Bear and the Piano">The Bear and the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£36.89</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="sophies-world_966/index.html"><img alt="Sophie's World" class="thumbnail" src="../media/cache/65/71/6571919836ec51ed54f0050c31d8a0cd.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="sophies-world_966/index.html" title="Sophie's World">Sophie's World</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£15.94</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="penny-maybe_965/index.html"><img alt="Penny Maybe" class="thumbnail" src="../media/cache/12/53/1253c21c5ef3c6d075c5fa3f5fecee6a.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="penny-maybe_965/index.html" title="Penny Maybe">Penny Maybe</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£33.29</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="maude-1883-1993she-grew-up-with-the-country_964/index.html"><img alt="Maude (1883-1993):She Grew Up with the country" class="thumbnail" src="../media/cache/f5/88/f5889d038f5d8e949b494d147c2dcf54.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="maude-1883-1993she-grew-up-with-the-country_964/index.html" title="Maude (1883-1993):She Grew Up with the country">Maude (1883-1993):She Grew Up ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£18.02</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="in-a-dark-dark-wood_963/index.html"><img alt="In a Dark, Dark Wood" class="thumbnail" src="../media/cache/23/85/238570a1c284e730dbc737a7e631ae2b.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="in-a-dark-dark-wood_963/index.html" title="In a Dark, Dark Wood">In a Dark, Dark ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£19.63</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="behind-closed-doors_962/index.html"><img alt="Behind Closed Doors" class="thumbnail" src="../media/cache/e1/5c/e15c289ba58cea38519e1281e859f0c1.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="behind-closed-doors_962/index.html" title="Behind Closed Doors">Behind Closed Doors</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£52.22</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="you-cant-bury-them-all-poems_961/index.html"><img alt="You can't bury them all: Poems" class="thumbnail" src="../media/cache/e9/20/e9203b733126c4a0832a1c7885dc27cf.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="you-cant-bury-them-all-poems_961/index.html" title="You can't bury them all: Poems">You can't bury them ...</a></h3>
 <div class="product_price">
 <p class="price_color">Ã‚Â£33.63</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>]

In [27]:
for article in articles:
    title=article.find('h3').find('a')['title']
    print(title)

In Her Wake
How Music Works
Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More
Chase Me (Paris Nights #2)
Black Dust
Birdsong: A Story in Pictures
America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana
Aladdin and His Wonderful Lamp
Worlds Elsewhere: Journeys Around ShakespeareÃ¢Â€Â™s Globe
Wall and Piece
The Four Agreements: A Practical Guide to Personal Freedom
The Five Love Languages: How to Express Heartfelt Commitment to Your Mate
The Elephant Tree
The Bear and the Piano
Sophie's World
Penny Maybe
Maude (1883-1993):She Grew Up with the country
In a Dark, Dark Wood
Behind Closed Doors
You can't bury them all: Poems

In [36]:
for article in articles:
    title=article.find('h3').find('a')['title']
    price=article.select_one("p.price_color").text.split('£')[1]
    print(price)

12.84
37.32
30.52
25.27
34.53
54.64
22.50
53.13
40.30
44.18
17.66
31.05
23.82
36.89
15.94
33.29
18.02
19.63
52.22
33.63

In [42]:
items=[]
for article in articles:
    title=article.find('h3').find('a')['title']
    price=article.select_one("p.price_color").text.split('£')[1]
    rating_element=article.select_one("p.star-rating")
    ratting=rating_element["class"][1]
    items.append([title,price,ratting])

In [98]:
items=[]
for article in articles:
    title=article.find('h3').find('a')['title']
    price=article.select_one("p.price_color").text.split('£')[1]
    rating_element=article.select_one("p.star-rating")
    ratting=rating_element["class"][1]
    availability = soup.find_all("p", class_="instock availability")
    for item in availability:
        avail=(item.get_text(strip=True))
    items.append([title,price,ratting,avail])

In [99]:
import pandas as pd

In [100]:
df=pd.DataFrame(items,columns=['Book Title','Book Price','Book Rating',"Stcok"])
df

,Book Title,Book Price,Book Rating,Stcok
0,In Her Wake,12.84,One,In stock
1,How Music Works,37.32,Two,In stock
2,Foolproof Preserving: A Guide to Small Batch J...,30.52,Three,In stock
3,Chase Me (Paris Nights #2),25.27,Five,In stock
4,Black Dust,34.53,Five,In stock
5,Birdsong: A Story in Pictures,54.64,Three,In stock
6,America's Cradle of Quarterbacks: Western Penn...,22.50,Three,In stock
7,Aladdin and His Wonderful Lamp,53.13,Three,In stock
8,Worlds Elsewhere: Journeys Around ShakespeareÃ...,40.30,Five,In stock
9,Wall and Piece,44.18,Four,In stock
10,The Four Agreements: A Practical Guide to Pers...,17.66,Five,In stock
11,The Five Love Languages: How to Express Heartf...,31.05,Three,In stock
12,The Elephant Tree,23.82,Five,In stock
13,The Bear and the Piano,36.89,One,In stock
14,Sophie's World,15.94,Five,In stock
15,Penny Maybe,33.29,Three,In stock
16,Maude (1883-1993):She Grew Up with the country,18.02,Two,In stock
17,"In a Dark, Dark Wood",19.63,One,In stock
18,Behind Closed Doors,52.22,Four,In stock
19,You can't bury them all: Poems,33.63,Two,In stock

In [45]:
df.dtypes

Book Title     object
Book Price     object
Book Rating    object
dtype: object

In [46]:
df.ndim

2

In [48]:
df.head()

                                          Book Title Book Price Book Rating
0                                        In Her Wake      12.84         One
1                                    How Music Works      37.32         Two
2  Foolproof Preserving: A Guide to Small Batch J...      30.52       Three
3                         Chase Me (Paris Nights #2)      25.27        Five
4                                         Black Dust      34.53        Five

In [49]:
df.tail()

                                        Book Title Book Price Book Rating
15                                     Penny Maybe      33.29       Three
16  Maude (1883-1993):She Grew Up with the country      18.02         Two
17                            In a Dark, Dark Wood      19.63         One
18                             Behind Closed Doors      52.22        Four
19                  You can't bury them all: Poems      33.63         Two

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Book Title   20 non-null     object
 1   Book Price   20 non-null     object
 2   Book Rating  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [101]:
df.to_csv("Data1.csx")